import os

PHYSICAL_PORT_NAME = "DDJ-400 MIDI 1"
VIRTUAL_PORT_NAME = "DDJ400 Bridge"
DISPLAY_PORT = os.environ.get("DISPLAY_PORT", "/dev/ttyACM0")
DISPLAY_BAUDRATE = int(os.environ.get("DISPLAY_BAUDRATE", "115200"))
DISPLAY_MANUFACTURER_ID = 0x7D
DISPLAY_REFRESH_INTERVAL = 1.0
DISPLAY_BPM_PLACEHOLDER = "-.-"
DISPLAY_KEY_PLACEHOLDER = "--"